//! Types and functions for executing plans generated by a [`planner`](crate::planner)s.

mod par_solver;
mod solve_error;

pub(crate) use par_solver::par_solve;
pub use solve_error::{Reason, SolveError};
